#Read file to numpy

Download the Iris dataset [here](https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv) that we already analyzed in ```EXP 1``` and upload the file to your local filesystem. (In case you are using Google Collaboratory, click the file icon on the left sidebar, and upload there.)

The following lines of code will read the ```iris.csv``` file into a Numpy ndarray called ```data```.

In [0]:
import numpy as np
data = np.genfromtxt("iris.csv",delimiter=',')

Look at its ```shape``` of the ```ndarray``` and observe its entries.

Clearly all the entries of the first row, and the entries of the last column are not numerical values (The first row describes the column, and the last column in all the other rows specifies the name of the species of flowers - these are all alphanumeric strings). Those are not of any interest to us in this experiment.

In [0]:
print("Shape of data:",data.shape)
print(data)

Slice the ```ndarray``` to exclude the first row and last column, i.e., take the first four columns from all the rows starting from the second row onwards.

In [0]:
# Remove the entire 1st row; and
# 5th column in all other rows
data = None

Reprint the data to check if the array has been sliced as required.

The shape should reflect the fact that one row and one column have been removed.

In [0]:
print("Shape of data:",data.shape)
print(data)

Find the mean and the variance of all the columns using methods from the NumPy module.

You will find both mean and variance as two ```ndarrays```, each containing four values for the four columns.

In [0]:
mean = None #Find the mean
variance = None #Find the variance 
print("Mean:",mean)
print("Variance",variance)

'''
The expected output of this cell is -
Mean: [5.84333333 3.05733333 3.758      1.19933333]
Variance [0.68112222 0.18871289 3.09550267 0.57713289]
'''

# Find the covariance matrix

The sliced data (i.e. the 2D ndarray obtained after removing the first row and last column) can be imagined as a matrix. Find the covariance matrix of the sliced data using methods available in the NumPy module -

WARNING: You may need to transpose the matrix before you can apply the required method. (The ```.T``` argument gives the transpose of a ```ndarray``` matrix. So, ```data.T``` will give the transpose of ```data```.)

In [0]:
cov = None #Find the covariance matrix
print("Covariance Matrix")
print(cov)
'''
The expected output of this cell is -
[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]
'''

#Find the Eigen values and Eigen Vectors

Once you have obtained the covariance matrix in the above step, find the Eigen values and the corresponding Eigen vectors using methods in the NumPy module -

In [0]:
# Write code to find the Eigen values and Eigen vectors here
eigen_values = None
eigen_vectors = None
print("Eigen values:",eigen_values)
print("Eigen vectors:")
print(eigen_vectors)
'''
The expected output of this cell is -
-----------------------------------------------------------
Eigen values: [4.22824171 0.24267075 0.0782095  0.02383509]
Eigen vectors:
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]
'''

#Sort the Eigen values

Once you have found out the Eigen values above, sort them in ascending order.

Sort the Eigen vectors in the order in which their associated Eigen values were sorted.

In [0]:
# Write code to sort here
sorted_eigen_vector = None
print("Sorted Eigen Vectors:")
print(sorted_eigen_vector)
'''
The expected output of this cell is -
-----------------------------------------------------------
Sorted Eigen Vectors:
[[ 0.3582892   0.07548102  0.54583143  0.75365743]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 ]
'''

#Good Job!

You have finished coding almost the entirety of the **Principal Component Analysis** (PCA) algorithm, which is a very important algorithm in  Machine Learning. Congratulations!